#!/bin/bash

# 注:ポート番号は固定
docker run -it --rm \
  --name $1 \
  -p 8080:8080 \
  -e SAKURACLOUD_ACCESS_TOKEN \
  -e SAKURACLOUD_ACCESS_TOKEN_SECRET \
  -e SAKURACLOUD_ZONES \
  -e SAKURACLOUD_TRACE_MODE \
  -e SACLOUD_BALUS_RECEIVE_PATH \
  -e SACLOUD_BALUS_RECEIVE_SECRET \
  -e SACLOUD_BALUS_SEND_TOKEN \
  -e SACLOUD_BALUS_SEND_SECRET \
  -e SACLOUD_BALUS_SEND_MODULE_ID \
  -e SACLOUD_BALUS_DEBUG \
  $1:latest ${@:2}